@startuml
class ObsidianBoy {
  -obsidian_interface: ObsidianInterface
  -daily_note_processor: DailyNoteProcessor
  -researcher: Researcher
  -note_creator: NoteCreator
  -note_tagger: NoteTagger
  -distilled_note_updater: DistilledNoteUpdater
  -ai_review_loop: AIReviewLoop
  -human_review_interface: HumanReviewInterface
  -terminal_interface: TerminalInterface
  +run()
  -define_workflow()
  -execute_workflow()
}
class ObsidianInterface {
  +list_daily_notes()
  +read_daily_note()
  +create_temp_note()
  +update_note()
  +get_existing_tags()
  +move_temp_to_vault()
}
class DailyNoteProcessor {
  +extract_entries()
}
class Researcher {
  -web_scraper: WebScraper
  -memory_manager: MemoryManager
  +research_entry()
}
class WebScraper {
  +scrape()
}
abstract class KnowledgeBase {
  {abstract} +store()
  {abstract} +retrieve()
}
class FileSystemKnowledgeBase {
  +store()
  +retrieve()
}
class MemoryManager {
  -knowledge_base: KnowledgeBase
  +store_content()
  +retrieve_content()
  +prepare_context()
}
class NoteCreator {
  +create_note()
}
class NoteTagger {
  +tag_note()
  +extract_existing_tags()
}
class DistilledNoteUpdater {
  +update_distilled_note()
}
class AIReviewLoop {
  +review_content()
  +provide_feedback()
  +refine_content()
}
class HumanReviewInterface {
  +review_new_notes()
  +review_note_changes()
}
class DiffGenerator {
  +generate_diff()
}
class TerminalInterface {
  +display_menu()
  +get_user_input()
  +show_daily_notes()
  +select_daily_notes()
}

ObsidianBoy --> ObsidianInterface
ObsidianBoy --> DailyNoteProcessor
ObsidianBoy --> Researcher
ObsidianBoy --> NoteCreator
ObsidianBoy --> NoteTagger
ObsidianBoy --> DistilledNoteUpdater
ObsidianBoy --> AIReviewLoop
ObsidianBoy --> HumanReviewInterface
ObsidianBoy --> TerminalInterface
Researcher --> WebScraper
Researcher --> MemoryManager
MemoryManager --> KnowledgeBase
KnowledgeBase <|-- FileSystemKnowledgeBase
HumanReviewInterface --> DiffGenerator
@enduml