@startuml
class ObsidianBoy {
  +run()
  -define_workflow()
  -execute_workflow()
}
class FileSystemInterface {
  +list_daily_notes()
  +read_daily_note()
  +create_temp_note()
  +update_note()
  +get_existing_tags()
  +move_temp_to_vault()
}
class DailyNoteProcessor {
  +extract_entries()
}
class GenericResearcher {
  +research_entry()
}
class WebScraper {
  +scrape()
}
abstract class KnowledgeBase {
  {abstract} +store()
  {abstract} +retrieve()
}
class FileSystemKnowledgeBase {
  +store()
  +retrieve()
}
class ContentProcessor {
  +prepare_context()
}
class NoteCreator {
  +create_note()
}
class NoteTagger {
  +tag_note()
  +extract_existing_tags()
}
class DistilledNoteUpdater {
  +update_distilled_note()
}
class AIReviewLoop {
  +review_content()
  +provide_feedback()
  +refine_content()
}
class HumanReviewInterface {
  +review_new_notes()
  +review_note_changes()
}
class DiffGenerator {
  +generate_diff()
}
class TerminalInterface {
  +display_menu()
  +get_user_input()
  +show_daily_notes()
  +select_daily_notes()
}

ObsidianBoy --> FileSystemInterface
ObsidianBoy --> DailyNoteProcessor
ObsidianBoy --> GenericResearcher
GenericResearcher --> WebScraper
GenericResearcher --> KnowledgeBase
KnowledgeBase <|-- FileSystemKnowledgeBase
GenericResearcher --> ContentProcessor
ObsidianBoy --> NoteCreator
ObsidianBoy --> NoteTagger
ObsidianBoy --> DistilledNoteUpdater
ObsidianBoy --> AIReviewLoop
ObsidianBoy --> HumanReviewInterface
ObsidianBoy --> TerminalInterface
HumanReviewInterface --> DiffGenerator
@enduml